### ISSUE TITLE
Request to change force update shortcut key

### ISSUE THREAD

**Issue by inchanS** [vitorgalvao/pin-plus-workflow#1]
### Workflow version

2023.2

### Alfred version

5.0.6 [2110]

### macOS version

Ventura 13.3.1

### Debugger output

```alfred_debugger
I am reaching out with a suggestion rather than an error report.
```

### More details

Hello,
I am currently using the Pin Plus workflow, and it has been incredibly useful for me. I am reaching out with a suggestion rather than an error report.

I use a different keyboard instead of the built-in one on my MacBook. However, the current workflow has a shortcut for force cache update set to fn + enter, which is only available on the MacBook keyboard. This means I am unable to use this command on my keyboard.

Is it possible to add the option for users to configure the workflow with their preferred shortcut combination or to allow hotkey mapping? Alternatively, using a command like "pupdate" to execute the force update would also be helpful.

Thank you.

**Comment by vitorgalvao** [comment]
Forcing a cache rebuild is to be avoided, it should only be done when really needed. But the workflow does include an [External Trigger](https://www.alfredapp.com/help/workflows/triggers/external/) so you can set that up yourself in a different workflow with a [Keyword Input](https://www.alfredapp.com/help/workflows/inputs/keyword/) connected to a [Call External Trigger Output](https://www.alfredapp.com/help/workflows/outputs/call-external-trigger/).
